[general]
import = ["/home/dawid/.config/alacritty/themes/current-theme.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Maple Mono"

[font.bold_italic]
family = "Maple Mono"
style = "Bold Italic"

[font.italic]
family = "Maple Mono"
style = "Italic"

[font.normal]
family = "Maple Mono"

[font.glyph_offset]
y = 6

[font.offset]
y = 12

[window]
dynamic_padding = true

[window.padding]
x = 10
y = 10
