[buildPlans.Iosevka1823]
family = "Iosevka1823"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

  [buildPlans.Iosevka1823.variants]
  inherits = "ss04"

  [buildPlans.Iosevka1823.ligations]
  inherits = "php"

[buildPlans.Iosevka1823.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Iosevka1823.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.Iosevka1823.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.Iosevka1823.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Iosevka1823.widths.Condensed]
shape = 500
menu = 3
css = "condensed"

[buildPlans.Iosevka1823.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.Iosevka1823.widths.SemiCondensed]
shape = 548
menu = 4
css = "semi-condensed"
